#!/usr/bin/env python3
"""
goldbach_comet_from_csv.py — Generate Goldbach comet plot from Rust CSV output

Takes a CSV file generated by Rust siliq engine and creates a comet visualization.
"""

import csv
import sys
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path


def load_csv_counts(csv_path):
    """Load pair counts from Rust CSV output (siliq_*.csv)"""
    ns = []
    counts = []
    
    try:
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    n = int(row['n'])
                    pair_count = int(row['pair_count'])
                    ns.append(n)
                    counts.append(pair_count)
                except (ValueError, KeyError):
                    continue
    except FileNotFoundError:
        print(f"Error: File {csv_path} not found")
        return None, None
    
    if not ns:
        print(f"Error: No valid data in {csv_path}")
        return None, None
    
    return np.array(ns), np.array(counts)


def generate_comet_plot(ns, counts, output_path='goldbach_comet.png', title_suffix=''):
    """Generate and save comet plot"""
    fig, ax = plt.subplots(figsize=(14, 6), dpi=150)
    
    # Scatter plot with transparency
    ax.scatter(ns, counts, s=0.3, c='steelblue', alpha=0.4, rasterized=True)
    
    ax.set_xlabel('n (even integer)', fontsize=12)
    ax.set_ylabel('g(n) = # Goldbach pairs', fontsize=12)
    
    n_max = ns.max() if len(ns) > 0 else 0
    title = f'Goldbach Comet — Pair Density {title_suffix}'
    if n_max > 0:
        title += f'\n(n = 4 to {n_max:,})'
    
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle=':')
    
    # Statistics
    avg_count = np.mean(counts) if len(counts) > 0 else 0
    max_count = np.max(counts) if len(counts) > 0 else 0
    min_count = np.min(counts) if len(counts) > 0 else 0
    
    stats_text = f'Mean: {avg_count:.1f} | Min: {int(min_count)} | Max: {int(max_count)}'
    ax.text(0.98, 0.02, stats_text, transform=ax.transAxes, 
            fontsize=10, ha='right', va='bottom',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"✓ Saved {output_path}")
    plt.close()


def main():
    if len(sys.argv) < 2:
        print("Usage: python goldbach_comet_from_csv.py <csv_file> [output_path]")
        print()
        print("Example:")
        print("  python goldbach_comet_from_csv.py siliq_2000000.csv goldbach_comet.png")
        print("  python goldbach_comet_from_csv.py siliq_100000000.csv")
        sys.exit(1)
    
    csv_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else 'goldbach_comet.png'
    
    print(f"Loading {csv_path}...")
    ns, counts = load_csv_counts(csv_path)
    
    if ns is None or counts is None:
        sys.exit(1)
    
    print(f"Loaded {len(ns)} data points")
    print(f"Range: n = {ns.min():.0f} to {ns.max():.0f}")
    print(f"Pair counts: min={counts.min():.0f}, max={counts.max():.0f}, avg={counts.mean():.1f}")
    
    # Determine title suffix from file
    file_stem = Path(csv_path).stem
    if 'siliq' in file_stem:
        n_val = file_stem.split('_')[-1]
        try:
            n_int = int(n_val)
            title_suffix = f'[4, {n_int:,}]'
        except:
            title_suffix = ''
    else:
        title_suffix = ''
    
    print(f"\nGenerating comet plot...")
    generate_comet_plot(ns, counts, output_path, title_suffix)
    
    print(f"Done!")


if __name__ == '__main__':
    main()
